### ISSUE TITLE
Compatibility with 68k

### ISSUE THREAD

**Issue by toncho11** [AcceleratedLinux/accelerated-linux#1]
Hi,

I would like to try it on: General Automation 1620 with Motorola 68020 CPU at 12 Mhz.
Is accelerated-linux compatible with Motorola 68020?

**Comment by jeffshaw** [comment]
We have a few targets which support 68020, so you should be able to configure it for the General Automation 1620. Have a look at the Atari target in vendors/Atari/Atari. This should still work on an Atari emulator like Aranym.
